### ISSUE TITLE
문제가 있습니다.

### ISSUE THREAD

**Issue by minjunkim5876** [minjunkim5876/Project_Owl#1]
### 문제
**서버요청이 안됌**
확인할 사항

- [x] 소스파일

- [ ] 클라우드환경

- [ ] 새로고침

**화면모습**

![스크린샷(1)](https://github.com/minjunkim5876/Project_Owl/assets/110665712/a01b44d4-d289-4d3f-845b-47b611e13159)

**Comment by KimJeongHoon190** [comment]
문제 없는데?

**Comment by minjunkim5876** [comment]
알겠습니다!

**Comment by minjunkim5876** [comment]
문제가 해결 됐습니다.
